services:
  parse:
    container_name: parse
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app_src
    env_file:
      - .env
    ports:
      - ${APP_PORT}

  redis:
    container_name: "event-bus-parse"
    image: redis:6-alpine
    ports:
      - "6379:6379"