spring:
  application:
    name: "Parse Service"
  data:
    redis:
      host: localhost
      port: ${REDIS_HOST}

stream:
  format: ${STREAM_KEY_FORMAT}
  validate: ${STREAM_KEY_VALIDATE}

groups:
  parser: ${GROUP_ID}

server:
  port: ${SERVER_PORT}
