spring:
  application:
    name: "Parse Service"
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

stream:
  format: ${STREAM_KEY_FORMAT}
  format-response: "abc"
  validate: ${STREAM_KEY_VALIDATE}
  lint-request: "12345"
  lint-response: "54321"

groups:
  parser: ${GROUP_ID}

server:
  port: ${SERVER_PORT}  # Corrected typo

logging:
  level:
    root: INFO
    com.ingsis.parse: INFO  # Adjust to DEBUG if needed for troubleshooting