spring:
  application:
    name: "Parse Service"
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

stream:
  format: ${STREAM_KEY_FORMAT}
  validate: ${STREAM_KEY_VALIDATE}

groups:
  parser: ${GROUP_ID}

server:
  port: ${SEVER_PORT}
