spring:
  application:
    name: "Parse Service"
  data:
    redis:
      host: localhost
      port: ${REDIS_HOST}

stream:
  key: ${STREAM_KEY}

groups:
  format: ${FORMAT_ID}

server:
  port: ${SERVER_PORT}
